# Generated by Django 5.0.2 on 2024-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Recently Used', 'Recently Used'), ('Used', 'Used'), ('Old', 'Old')], default='Brand New', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('Top Deals Of The Day', 'Top Deals Of The Day'), ('Top Selling Products', 'Top Selling Products'), ('Top Featured Products', 'Top Featured Products'), ('recommended', 'Recommended')], max_length=200),
        ),
    ]
