# Generated by Django 5.0.2 on 2024-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_status_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('Top Deals Of The Day', 'Top Deals Of The Day'), ('Top Selling Products', 'Top Selling Products'), ('Top Featured Products', 'Top Featured Products'), ('Recommended', 'Recommended')], max_length=200),
        ),
    ]
