# Generated by Django 5.0.2 on 2024-02-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
