# Generated by Django 5.0.2 on 2024-02-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.section'),
        ),
    ]
